### ISSUE TITLE
Twig function "pattern_configuration" is undefined

### ISSUE THREAD

**Issue by miloskroulik** [wingsuit-designsystem/wingsuit_companion#1]
I've installed wingsuit to my existing codebase using the same process as BLT does. It looks like twig templates are recognized correctly, but the function is unknown. I also build storybook, just in case. Can you help me with fixing this error, please? I will provide more info if needed.

`Twig\Error\SyntaxError: Unknown "pattern_configuration" function. in Twig\ExpressionParser->getFunctionNodeClass() (line 16 of themes/custom/wingsuit/dist/app-drupal/atomic/patterns/03-organisms/container/container.twig).`

**Comment by christianwiedemann** [comment]
pattern_configuratoin is part of ui_patterns_settings:2. This should be installed with wingsuit_companion. Have you installed wingsuit_companion or did you install UI patterns seperatly

**Comment by christianwiedemann** [comment]
Ah you posted it inside wingsuit_companion :). 

Seems that UI patterns settings 1.x is choosen.
https://github.com/wingsuit-designsystem/wingsuit_companion/blob/8.x-1.x/wingsuit_companion.info.yml

Propably `composer require drupal/ui_patterns_settings:^2.0@beta` will help.

**Comment by miloskroulik** [comment]
Thanks, I was unsure what's the best place to post this issue. I will try that.

**Comment by miloskroulik** [comment]
It works fine, thanks again.
